### PR TITLE
Version 3.25.2 b1

### PR DESCRIPTION
**Pull request by cowwoc**
* Updated to CMake 3.25.2-b1.
* Backported to JDK 8.
* Added support for ARM 32-bit platforms.

### CODE REVIEW

**Comment by jimfcarroll** [comment]
Hey thanks. It works on my aarch64 build. A few notes:

1. I tried to build setting the local repository as it seems your supposed to but one of the integration tests failed anyway.
2. I commented out the integration tests in the pom file (since -DskipTests didn't disable them) so I could get the plugin jar file in my repo (if the integration tests fail the packaging step appears to be skipped).
3. I ran my native builds using the results and everything built fine.

Thanks. You can close me PR.

**Comment by jimfcarroll** [comment]
Oh... one more:

4. I had to disable the -Werror setting. Building using jdk 17 with the source set to 8 results in a warning that trips the failure.

**Comment by cowwoc** [comment]
@jimfcarroll Out of curiosity, which integration test was failing for you? One of them is meant to fail (dashboard test).

**Comment by jimfcarroll** [comment]
The dashboard test "passed," at least according to maven. 

```
[INFO]   The build exited with code 1. See /home/jim/src/cmake-maven-project/cmake-maven-plugin/target/it/binaries-on-path-test/build.log for details.
[INFO]           binaries-on-path-test/pom.xml .................... FAILED (24.1 s)
```

If you want the entire output I can get it for you.

**Comment by jimfcarroll** [comment]
Looking at the build log referred to above, this seems like the problem (but I'm not sure; it's just a warning):

```
[INFO] Downloading from local.central: file:///home/jim/.m2/repository/com/googlecode/cmake-maven-project/cmake-binaries/3.25.2-b1/cmake-binaries-3.25.2-b1-linux-arm_64.jar
[WARNING] Could not validate integrity of download from file:///home/jim/.m2/repository/com/googlecode/cmake-maven-project/cmake-binaries/3.25.2-b1/cmake-binaries-3.25.2-b1-linux-arm_64.jar
org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available
    at org.eclipse.aether.internal.impl.AbstractChecksumPolicy.onNoMoreChecksums (AbstractChecksumPolicy.java:72)
    at org.eclipse.aether.connector.basic.ChecksumValidator.validate (ChecksumValidator.java:126)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:469)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:383)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0 (RunnableErrorForwarder.java:73)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute (BasicRepositoryConnector.java:635)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get (BasicRepositoryConnector.java:280)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads (DefaultArtifactResolver.java:581)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:478)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:278)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:255)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:296)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:197)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:146)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:535)
    at org.apache.maven.plugin.dependency.fromConfiguration.AbstractFromConfigurationMojo.getArtifact (AbstractFromConfigurationMojo.java:257)
    at org.apache.maven.plugin.dependency.fromConfiguration.AbstractFromConfigurationMojo.getProcessedArtifactItems (AbstractFromConfigurationMojo.java:171)
    at org.apache.maven.plugin.dependency.fromConfiguration.UnpackMojo.getProcessedArtifactItems (UnpackMojo.java:144)
    at org.apache.maven.plugin.dependency.fromConfiguration.UnpackMojo.doExecute (UnpackMojo.java:101)
    at org.apache.maven.plugin.dependency.AbstractDependencyMojo.execute (AbstractDependencyMojo.java:167)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:260)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:172)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:100)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:821)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:270)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[WARNING] Checksum validation failed, no checksums available from local.central for file:///home/jim/.m2/repository/com/googlecode/cmake-maven-project/cmake-binaries/3.25.2-b1/cmake-binaries-3.25.2-b1-linux-arm_64.jar
```

**Comment by cowwoc** [comment]
@jimfcarroll That's odd. I assume that the Maven build failed due to the failing test?

Is this error reproducible? Or did this only happen once?

I've never seen this on my local computer or on GitHub Actions, so I'm leaning towards ignoring it for now.

**Comment by jimfcarroll** [comment]
It happens every time. In order to build a jar I could use I commented out the section that hooks the maven lifecycle in order to enable the integration tests and built without running them.

The final jar file I used to build my native projects on my aarch64 system and it worked fine.

**Comment by cowwoc** [comment]
@jimfcarroll What environment is this reproducible on? (OS, JDK vendor/version, mvn command line)

**Comment by jimfcarroll** [comment]
It's running on an aarch64 system inside an Ubuntu 20.04 docker container with OpenJDK 17 installed.

```
jim@26ffaa147699:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

```
jim@26ffaa147699:~$ uname -a
Linux 26ffaa147699 4.2.8 #1 SMP Thu Jan 12 09:00:52 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
```

```
jim@26ffaa147699:~$ mvn --version
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: /opt/maven
Java version: 17.0.5, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-arm64
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.2.8", arch: "aarch64", family: "unix"
```

```
jim@26ffaa147699:~$ java --version
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode)
```

**Comment by jimfcarroll** [comment]
the maven command line is:

```
mvn -DlocalRepositoryUrl=file:///home/jim/.m2/repository clean install
```

Or, from the cmake-plugin subproject it does the same thing even if I just run `mvn clean install`

**Pull request merged**
