### PR TITLE
Updated CMake to latest version

### PR DESCRIPTION
**Pull request by cowwoc**
Updated dependencies/plugins to latest versions.
Fixed Findbugs warnings.

### CODE REVIEW

**Comment by ksclarke** [comment]
Looks good to me @cowwoc 

Also, what do you use for an editor? And does it have an exportable style configuration? I have noticed before our space vs. tab (for indention) formatting differences (and a few others too). It would be good for me to get on the same page as you to eliminate those types of formatting differences.

**Comment by cowwoc** [comment]
@ksclarke I use NetBeans 8.2. Which editor do you use? We could try using http://editorconfig.org ... I haven't tried out before but it sounds ideal.

**Comment by ksclarke** [comment]
@cowwoc I use Eclipse 4.6. I also haven't tried editorconfig.org before but it does look very interesting. I'll look into it.

**Comment by cowwoc** [comment]
Man... I haven't coded in C/C++ in over 7 years. I can't believe how 
much joy I just got when I finally got the code to compile with CMake :) 
I absolutely love how much easier CMake projects are to debug than the 
alternative.

Question for you...

I created multiple Maven profiles in my Java application, one per 
platform. Windows has 4 profiles:

 1. i386, debug
 2. i386, release
 3. amd64, debug
 4. amd64, release

I configured one of them to get activated automatically if the current 
platform is Windows. I was expecting this behavior to turn off if I 
explicitly activated another profile, but instead *both* profiles were 
active.

Is this normal?

If so, should we really be using activation by OS? Seems kind of fragile 
if developers wish to build for any other platform (and not build the 
default).

Gili

**Comment by cowwoc** [comment]
I took a look at the Netbeans plugin for editorconfig and it's not 
really complete.

It's probably best if I just communicate my settings to you verbally.

I use a max width of 100 characters (the editor line-wraps past this 
point) and tabs for indentation.

There are other settings, such as the order of imports but I don't think 
we're run across such problems in the past, have we?

Gili

**Comment by ksclarke** [comment]
Profiles have to be defined in the pom so that your system conditions only match one definition (unless you want to have multiple profiles active... there are cases for that, too). If you have one profile that gets activated by windows OS and you have another that's windows OS + a system property, both will get activated when you trigger the system property one on Windows. You'd have to define the profiles so that each only matches one specific configuration/option. That can be a pain sometimes because of the limited options in condition matching in Maven profile activation (they need better boolean support or something, imho). 

I think line wraps and tabs/spaces are the only ones I've noticed. I have set my editor set to not reformat code that I haven't touched (so while I do have an import order defined I don't think I've every seen it reorganize cmake-maven-project code). I'll set me project settings to tabs and 100 and see if I run into anything else in the future. Thanks.

**Comment by cowwoc** [comment]
The problem I saw was one profile activated by a <platform> trigger, and 
another one activated by a -P command-line option.

So for example, the IDE would pass -P win32-release while <platform> 
would activate "win32-debug" and both would end up building. I expected 
the command-line activation to disable any other profile activation. 
Anyway, I guess it's fine once you know about it... so if someone really 
only wants to run one profile, they'd need to explicitly disable all the 
auto-activated ones.

Gili

**Comment by ksclarke** [comment]
Hmm, okay, I was assuming both profiles were defined in the POM. I can see how one would have an expectation that supplying a command line profile would overwrite the ones defined in the POM. It would sort of break the additive nature of Maven profiles in general, but it would be a nice short-hand convenience. File a ticket for it and maybe one of us will get to it? :-)

**Comment by cowwoc** [comment]
@ksclarke I guess what I'm saying is that we should consider removing OS-triggered profile selection.

**Comment by ksclarke** [comment]
I like it for a nice out of the box simple working setup and you can override it with more complex profile configurations in the POM itself. I wonder what percentage of the users use the simple route versus more complex configurations(?) Probably no way to know. If you want to, though, that's fine with me. We'd just need a little more documentation on profile setup I think.

**Comment by ksclarke** [comment]
Guess you could ask the mailing list if folks would miss automatic OS-triggered profile selection to get a general opinion(?)

**Comment by cowwoc** [comment]
We have a mailing list? :) I remember we used to but I don't remember the address. Now would be a good time to add it to the README.

**Comment by ksclarke** [comment]
Heh, or maybe we lost it when we left Google Code? I'm not sure. :-)

**Comment by cowwoc** [comment]
Found it! Looks like it's still active :) https://groups.google.com/forum/#!forum/cmake-maven-project-users

**Comment by cowwoc** [comment]
So to recap: I prefer removing the profile activation, but I don't feel too strongly about it. That said, we should document the behavior no matter which way we go.

**Comment by ksclarke** [comment]
Hmm, I see I'm subscribed but I don't remember ever seeing that last message.

My recap: I'd prefer keeping default OS profile activation but also don't feel too strongly about it. I'm not very inclined to do the work, myself, to remove it but wouldn't mind if you wanted to. I wouldn't mind documenting that Maven profiles are additive, so they have to be created to be exclusive of one another (if this behavior isn't desired), and that profiles activated on the command line don't overrule those defined in the POM, though.

**Comment by cowwoc** [comment]
@ksclarke Can you please merge and release a new version with this pull request? My project depends on this library and I plan on making a release in the upcoming week.

**Comment by ksclarke** [comment]
@cowwoc I'm confused. This is your project. You can release new versions. You shouldn't need to be held up by me.

**Comment by cowwoc** [comment]
@ksclarke I actually assumed this was *your* project as of the past couple of years as I have become less active on it ;) Anyway, no worries. Let's co-author it. I will go ahead and make a release. Thanks :)

**Comment by ksclarke** [comment]
Oh, heh, sorry. I've thought of myself as a helper and as you as the author (if I had forked, I would have changed the package names and reformatted to my style defaults<g>). Co-authoring is fine, but it would be good if you could do the release as I'm neck deep at the moment. Thanks!

**Comment by cowwoc** [comment]
@ksclarke One thing before I merge... The new build system reads the gpg password from settings.xml instead of prompting you each time.

You'll need to do two things to get this working:

1. Create a master password to settings-security.xml
2. Add a server entry to settings.xml containing gpg.passphrase:

```
<server>
  <id>gpg.passphrase</id>
  <passphrase>{anEncryptedPassword}</passphrase>
</server>
```

See https://maven.apache.org/guides/mini/guide-encryption.html for a detailed overview (it is surprisingly easy to set up).

Let me know if you have any concerns with this process.

**Pull request merged**
