### PR TITLE
Support for Solaris and AIX

### PR DESCRIPTION
**Pull request by whittlec**
I've edited the code so it will now build and execute on both Solaris and AIX (#12). The projects I was trying to build on these platforms using this plugin do now build successfully.

It doesn't download the binaries for these platforms since none are hosted on the CMake web site, so when building you do need to tell it where local copies are using -Dcmake.root.dir=... on the command line. I've not made it include those local copies when building the binaries artifact, so that remains empty.

### CODE REVIEW

**Comment by ksclarke** [comment]
So, the intention is to create empty classified jars for sunos and aix?

Running `mvn clean install -Psunos` (not on a sunos machine) results in tests failing with:

    Resolving expression: '${cmake.root.dir}': Detected the following recursive expression cycle in 'cmake.root.dir'

I need to look a little deeper into this still. Sorry for the delay.

**Comment by whittlec** [comment]
I think you make a good point about the empty jars. I think it would be difficult to populate them with an appropriate set of binaries since CMake doesn't provide them on their web site, but also that for Solaris there are multiple hardware architectures to consider: both x86_64 and Sparc. I also found that building CMake on Solaris 10 resulted in a binary that would not run on Solaris 11.3.

Do you think it would be sensible to include dummy versions of the binaries? Maybe shell scripts that fail stating that binaries should be obtained and referenced separately.

The way I had it building was to use `mvn clean install -Psunos -Dcmake.root.dir=/path/to/cmake`.

**Comment by cowwoc** [comment]
@whittlec My preference would be to shift as much of the work onto the developers of this plugin, away from end-users. Meaning, if you need to create a different JAR per architecture/version of Solaris, so be it. It is preferable to have one person deal with this headache as opposed to pushing it out to all users. Just my 2 cents.

**Comment by ksclarke** [comment]
I agree we don't want to push anything off on the users, but I think what we're saying with the "native" option is "if you want to use what's on your system, here is a way to do that". It's not the default (which is to download) but, if you choose, we'll support using what's installed locally.

I think there should be some sort of message if a person doesn't have their config quite right and gets to the point where those empty jars would be tried to be used. Shell scripts in them might be one way to do that. I kind of wonder whether those jars should be generated at all though, and whether the GenerateMojo should just step in if someone is trying to run on one of the OSes that doesn't have downloadable CMake binaries available (and also doesn't have the CMake binaries installed locally).

For running on the RPi, the default CMake root location would work even if someone didn't supply cmake.root.dir. I kind of think it should work that way by default and that the cmake.root.dir should be if someone wants to override the default location at which CMake would be found on a particular system (assuming it's been installed through the system's package manager, etc.) Maybe that's not assuming that it's in a particular location but determined by checking the system's PATH for the default location.

**Comment by cowwoc** [comment]
@ksclarke Agreed.

**Comment by whittlec** [comment]
The underlying issue has been fixed, in a more graceful manner than my attempt. Closing this pull request.

**Pull request closed without merging**
